@WebApi_HostAddress = http://localhost:5167

### 1. Logowanie Administratora
# Zwraca accessToken i refreshToken
POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@parking.pl",
  "password": "Admin@123!"
}

###

### 2. Logowanie Pracownika (GateController)
POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "jan.kowalski@parking.pl",
  "password": "Staff@123!"
}

###

### 3. Pobranie danych profilu (Wymaga wklejenia tokena)
@token = TUTAJ_WKLEJ_ACCESS_TOKEN
GET {{WebApi_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}

###

### 4. Odświeżenie tokenu
# Wymaga obu tokenów z odpowiedzi logowania
POST {{WebApi_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
  "accessToken": "{{token}}",
  "refreshToken": "TUTAJ_WKLEJ_REFRESH_TOKEN"
}
