@WebApi_HostAddress=http://localhost:5167

# 1. Pobierz wszystkie bramki
GET {{WebApi_HostAddress}}/api/gates
Accept: application/json

###

# 2. Pobierz bramkę "Wjazd 1" (Stałe ID z Seeder'a)
GET {{WebApi_HostAddress}}/api/gates/52f48199-bc0a-477c-afbe-78b59aced549
Accept: application/json

###

# 3. Pobierz bramkę "Wyjazd 1" (Stałe ID z Seeder'a)
GET {{WebApi_HostAddress}}/api/gates/1984c840-e04a-464f-8cad-861ef2e7abd1
Accept: application/json

###

# 4. Dodaj nową bramkę (Wymaga bycia zalogowanym - Staff/Admin)
# Dodaj nagłówek Authorization po zalogowaniu w auth_tests.http
POST {{WebApi_HostAddress}}/api/gates
Content-Type: application/json

{
  "name": "Brama A1",
  "location" : "Sektor Zachodni",
  "type": "Entry"
}

###

# 5. Walidacja (Błędna nazwa - znaki specjalne)
POST {{WebApi_HostAddress}}/api/gates
Content-Type: application/json

{
  "name": "Brama_#1",
  "location" : "Sektor 1",
  "type": "Entry"
}
